config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get '/auth/github/callback' => 'sessions#create'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  delete 'logout' => 'sessions#destroy'
  post 'comments' => 'comments#create'
  delete 'comment/:id' => 'comments#destroy', as: 'delete_comment'
  delete 'commercial/:id' => 'commercials#destroy', as: 'delete_commercial'
  resources :users, only: [:show] do
    resources :commercials, only: [:index, :show, :edit, :new]
  end
  resources :users, only: [:edit, :update]
  resources :commercials, only: [:index, :show, :create, :update]

  get 'mostcommercials' => 'users#most_commercial_user'
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    has_many :commercials
    has_many :states, through: :commercials
    has_many :comments
    has_many :commented_commercials, through: :comments, source: :commercial

    validates :username, presence: true, uniqueness: true

    def self.create_by_auth(auth)
        find_or_create_by(uid: auth[:uid]) do |u|
            u.username = auth[:info][:name]
            u.password = SecureRandom.hex
            u.email = auth[:info][:email]
        end
    end

    # --------- live coding ----------
    def self.commercial_user
        joins(:commercials).group(:username)
    end
    # ---------- end ----------------
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authentication_required, only: [:show, :edit, :update]
    # sign up
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end 
    end

    def show
    end

    def edit
    end

    def update
        @current_user.update(user_params)
        redirect_to user_path(@current_user)
    end

    # --------- live coding ----------
    def most_commercial_user
        users_hash = User.commercial_user.count
        # ['username', commercial_count]
        @most_user_data = users_hash.max_by{|username, commercial_count| commercial_count}
    end
    # --------- end ----------
    
    private
    
    def user_params
        params.require(:user).permit(:username, :password, :email, :phone_number)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def email(user)
        user.email ? user.email : 'None'
    end

    def phone_number(user)
        user.phone_number ? user.phone_number : 'None'
    end
end

app/views/users/_form.html.erb
<%= form.label :email, 'User Email:'%>
<%= form.email_field :email %><br>
<%= form.label :phone_number, 'User Phone Number:'%>
<%= form.text_field :phone_number %><br>
<%= form.label :password, 'User Password:'%>
<%= form.password_field :password %><br><br>
<%= form.submit submit %>

app/views/users/edit.html.erb
<div class='center'>
    <div class='content_center'>
        <h1>Edit <%= @current_user.username %>'s Info</h1>
        <%= form_for @current_user do |f|%>
            <%= render partial: 'form', locals: {form: f, submit: 'Edit User'} %>
        <% end %>
    </div>
</div>

app/views/users/most_commercial_user.html.erb
<h1>Most Commercial User</h1>

<h3>User Name: <%= @most_user_data[0] %></h3>
<h3>Commercial Number: <%= @most_user_data[1] %></h3>

app/views/users/new.html.erb
<div class='center'>
    <div class='content_center'>
        <h1>Create New User</h1>
        <br>
        <%= form_for @user, url: signup_path do |f|%>
            <% if @user.errors.any? %>
                <% @user.errors.full_messages.each do |message| %>
                    <div class='error_message'><%= message %></div>
                <% end %>
            <% end %>
            <%= f.label :username, 'User Name:'%>
            <%= f.text_field :username %><br>
            <%= render partial: 'form', locals: {form: f, submit: 'Create User'} %>
        <% end %>  
    </div>
</div>

app/views/users/show.html.erb
<div class='center'>
    <div class='info'>
        <p><strong>Name: </strong><%= @current_user.username %></p>
        <p><strong>Email: </strong><%= email(@current_user) %><p>
        <p><strong>Phone Number: </strong><%= phone_number(@current_user) %><p><br>
        
        <button><%= link_to "Edit #{@current_user.username}'s Info", edit_user_path(@current_user)%></button><br>
        <button><%= link_to 'See My Commercials', user_commercials_path(@current_user) %></button><br>
        <button><%= link_to 'See Commercials', commercials_path %></button>
    </div>
</div>