config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get '/auth/github/callback' => 'sessions#create'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  delete 'logout' => 'sessions#destroy'
  post 'comments' => 'comments#create'
  delete 'comment/:id' => 'comments#destroy', as: 'delete_comment'
  delete 'commercial/:id' => 'commercials#destroy', as: 'delete_commercial'
  resources :users, only: [:show] do
    resources :commercials, only: [:index, :show, :edit, :new]
  end
  resources :users, only: [:edit, :update]
  resources :commercials, only: [:index, :show, :create, :update]

  get 'mostcommercials' => 'users#most_commercial_user'
end

app/models/commercial.rb
class Commercial < ApplicationRecord
    belongs_to :user
    belongs_to :state
    has_many :comments
    has_many :users, through: :comments
    
    validates :title, :description, :state_id, presence: true

    def state_attributes=(state_hash)
        self.state = State.find_or_create_by(state_hash)
    end
    
    def self.desc_order
        order(updated_at: :desc)
    end

    def self.by_user(user_id)
        where(user: user_id)
    end

    def self.by_state(state_id)
        where(state: state_id)
    end

    def self.by_user_and_id(user_id, commercial_id)
        where(user: user_id, id: commercial_id)
    end
end

app/controllers/commercials_controller.rb
class CommercialsController < ApplicationController
    before_action :authentication_required

    def index
        @users = User.all
        @states = State.all
        if params[:user_id]
            # previde directly editting id
            if session[:user_id] == params[:user_id].to_i
                @user = @current_user
                @commercials = @user.commercials
            else
               redirect_to user_path(@current_user) 
            end
        else
            @commercials = Commercial.all
        end

        # filter section
        if params[:uid].present?||params[:state_id].present?
            # -------- refactor ---------
            @commercials = @commercials.by_user(params[:uid]) if params[:uid].present? 
            @commercials = @commercials.by_state(params[:state_id]) if params[:state_id].present?
            @commercials = @commercials.desc_order
            # -------- end ---------
        end

    end

    def show
        if params[:user_id]
            # prevent directly editting id
            if session[:user_id] == params[:user_id].to_i
                @user = @current_user
                @commercial = Commercial.by_user_and_id(@user, params[:id]).first
                redirect_to user_commercials_path(@user) if !@commercial   
            else
               redirect_to user_path(@current_user) 
            end
        else
            @commercial = Commercial.find(params[:id])
            @user = @commercial.user
        end
    end

    def new
        if params[:user_id].to_i == session[:user_id]
            @commercial = Commercial.new
            @state = State.new
        else
            redirect_to user_commercials_path(@current_user)
        end
    end

    def edit
        if params[:user_id].to_i == session[:user_id] && @commercial = Commercial.by_user_and_id(@current_user, params[:id]).first
            @state = @commercial.state
        else
            redirect_to user_commercials_path(@current_user)
        end
    end

    def create
        @commercial = @current_user.commercials.build(commercial_params)
        if @commercial.save
            redirect_to user_commercial_path(@current_user, @commercial)
        else
            redirect_to new_user_commercial_path(@current_user), flash: {errors: @commercial.errors.full_messages}
        end
    end

    def update
        @commercial = Commercial.find(params[:id])
        if @commercial.update(commercial_params)
            redirect_to user_commercial_path(@current_user, @commercial)
        else
            redirect_to edit_user_commercial_path(@current_user, @commercial), flash: {errors: @commercial.errors.full_messages}
        end
    end

    def destroy
        Commercial.find(params[:id]).destroy
        redirect_to user_commercials_path(@current_user)
    end

    private
    
    def commercial_params
        params.require(:commercial).permit(:title, :description, state_attributes:[:name])
    end
end

app/helpers/commercials_helper.rb
module CommercialsHelper
    def link_back(user)
        if params[:user_id]
            link_to "Back to #{user.username}'s Commericals Page", user_commercials_path(user)
        else
            link_to 'Back to Commericals Page', commercials_path
        end
    end

    def link_commercial(commerical, user)
        if user
            link_to commerical.title, user_commercial_path(user, commerical)
        else
            link_to commerical.title, commercial_path(commerical)
        end
    end
end

app/views/commercials/_form.html.erb
<%= form_for object do |f|%>
    <% if flash[:errors] %>
        <% flash[:errors].each do |message|%>
            <div class='error_message'><%= "* #{message}"%></div>
        <% end %>
    <% end %>
    <%= f.label :title, 'Title:' %>
    <%= f.text_field :title, size: '100'%><br><br>
    <%= f.label :description, 'Description: ' %><br>
    <%= f.text_area :description, size: '150x10' %><br><br>
    <%= f.label :state, 'State:' %>
    <%= f.fields_for :state, @state do |state_fields|%>
        <%= state_fields.text_field :name, list: "states_autocomplete" %>
        <datalist id="states_autocomplete">
            <% State.all.each do |state|%> 
                <option value="<%= state.name %>">
            <% end %>
        </datalist>
    <% end %>
    <br><br>
    <%= f.submit submit%>
<% end %>

app/views/commercials/edit.html.erb
<h2>Edit <%= @commercial.title%></h2><br>

<%= render partial: 'form', locals: {object: @commercial, submit: 'Update Commercial'}%><br>
<%= button_to 'Cancel', user_commercial_path(@current_user, @commercial), method: :get%>

app/views/commercials/index.html.erb
<h2><%= "#{@user.username}'s " if @user %>Commercials</h2>
<%= button_to('Create New Commercial', new_user_commercial_path, method: :get) if @user %><br>
<% if !params[:user_id] %>
    <%= form_tag commercials_path, method: :get do %>
        <%= label_tag :uid, 'Poster:' %>
        <%= select_tag "uid", options_from_collection_for_select(@users, "id", "username"), include_blank: true %>
        <%= label_tag :state_id, 'State:' %>
        <%= select_tag "state_id", options_from_collection_for_select(@states, "id", "name"), include_blank: true %>
        <%= submit_tag :'Filter' %>
    <% end %>
<% end %>

<div class='content'>
    <% @commercials.each do |commercial|%>
        <div class='info_commercial'>
            <h4 class='text_wrap'><strong><%= link_commercial(commercial, @user) %></strong></h4>
            <p><strong>State: </strong><%= commercial.state.name %></p>
            <p><strong>Updated Date: </strong><%= commercial.updated_at %></p>
            <p class='text_wrap'><%= commercial.description %></p>
        </div>
    <% end %>
</div>

app/views/commercials/new.html.erb
<h1>Crreat Commercial</h1>
<%= render partial: 'form', locals: {object: @commercial, submit: 'Create Commercial'}%>
<br>
<%= button_to 'Cancel', user_commercials_path(@current_user), method: :get%>

app/views/commercials/show.html.erb
<% if params[:user_id] %>
    <button><%= link_to 'Edit Commercial', edit_user_commercial_path(@user, @commercial)%></button><br>
    <button><%= link_to 'Delete Commercial', delete_commercial_path(@commercial), method: :delete %></button><br>
<% end %>
<button><%= link_back(@user) %></button>

<h2><%= @commercial.title %></h2>
<p class='info'><%= @commercial.description %></p>
<h3>Contect: </h3>
<div class='info'>
    <p>State: <%= @commercial.state.name %></p>
    <p>Email: <%= email(@user) %></p>
    <p>Phone Number: <%= phone_number(@user) %></p>
</div><br><br>

<%= form_for :comment, url: comments_path do |f|%>
    <%= f.text_area :content, size: "100x5", placeholder: 'Leave a comment here.' %>
    <%= f.hidden_field :user_id, value: @current_user.id %>
    <%= f.hidden_field :commercial_id, value: @commercial.id %><br>
    <%= f.submit :'Comment' %>
<% end %><br><br>

<% @commercial.comments.desc_order.each do |comment|%>
    <div>
        <h3><%= comment.user.username %> said:</h3>
        <p class='info'><%= comment.content %></p>
        <% if comment.user == @current_user %>
            <%= form_tag delete_comment_path(comment), method: :delete do %>
                <%= hidden_field_tag :commercial_id, @commercial.id %>
                <%= submit_tag :'Delete Comment'%>
            <% end %>
        <% end %>
    </div>
<% end %>