config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get '/auth/github/callback' => 'sessions#create'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  delete 'logout' => 'sessions#destroy'
  post 'comments' => 'comments#create'
  delete 'comment/:id' => 'comments#destroy', as: 'delete_comment'
  delete 'commercial/:id' => 'commercials#destroy', as: 'delete_commercial'
  resources :users, only: [:show] do
    resources :commercials, only: [:index, :show, :edit, :new]
  end
  resources :users, only: [:edit, :update]
  resources :commercials, only: [:index, :show, :create, :update]

  get 'mostcommercials' => 'users#most_commercial_user'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Commercials Board App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if logged_in? %>
            <%= link_to 'Log Out', logout_path, method: :delete, class: 'navbar-brand'%>
            <%= link_to "#{current_user.username}'s Profile", user_path(current_user), class: 'navbar-brand'%>
          <% else %>
            <%= link_to 'Log In', root_path, class: 'navbar-brand'%>
            <%= link_to 'Sign Up', signup_path, class: 'navbar-brand'%>
          <% end %>

        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            
          </ul>
        </div>
      </div>
    </div>


    <div class="container"  role="main">
      <%= yield %>
    </div>
  </body>
</html>